feat: create NewsAPI
FabianSig/DHBW-ASWE-Personal-Digital-Agent pull request #3
Opened 2024-10-26 15:19 UTC by Chaligula

basic connection of NewsAPI

2024-10-26 15:28 UTC, FabianSig requested changes
In das Github nicht den kompilierten Code pushen sondern den **Source Coude**

2024-10-26 15:29 UTC, NikomitK requested changes
Wo ist der code? Und der target Ordner sollte eigentlich nicht gepusht werden

2024-10-26 15:36 UTC, NikomitK commented
am besten commit reverten, damit das alles wieder clean draußen ist

2024-10-28 20:00 UTC, einBuegelbrett submitted a review, later dismissed
Schau dir an was ich geschrieben habe.

2024-10-30 19:58 UTC, Chaligula commented on Microservices/Speisekarte/src/main/java/nikomitk/personaldigitalagentmsspeisekarte/controller/SpeisekarteController.java
>  public class SpeisekarteController {
Das ist eine Datei aus dem Speisekarten Service, keine Ahnung wieso die bei dir angezeigt, wurde, bei mir ist die nicht

2024-11-02 14:08 UTC, NikomitK commented
Warum ist der ganze code doppelt? es sind 2 packages in src/main, die beide die gleiche struktur für die ganze application haben

2024-11-03 09:06 UTC, einBuegelbrett commented
@Chaligula 

Bitte löse die Merge-Konflikte auf und wenn du mit allen Änderungen fertig bist, klicke auch auf "Ready for review", damit wir wissen, dass wir es reviewen können.

![image](https://github.com/user-attachments/assets/458b2721-5a7a-4ad6-bfab-cdf0538dd6e4)

2024-11-03 13:45 UTC, NikomitK requested changes

2024-11-03 13:45 UTC, NikomitK commented on Microservices/News/src/main/java/Chaligula/news/controller/NewsController.java
> +@CrossOrigin(origins="*")
Bitte entfernen
```suggestion
```

2024-11-03 13:45 UTC, NikomitK commented on Microservices/News/src/main/java/Chaligula/news/dto/News.java
> +
Bitte die benötigten Informationen im Record einbauen

```suggestion
import java.util.List;

public record News(List<Article> articles) {
    public record Article(Source source, String author, String title, String description, String url, String urlToImage, String publishedAt) {
        public record Source(String id, String name) {
        }
    }
}

```

2024-11-04 10:40 UTC, NikomitK commented
Vergessen die changes zu pushen oder wird bei mir was nicht angezeigt?

2024-11-04 19:35 UTC, NikomitK approved these changes
Hey Ralf,

vielen Dank für deinen Einsatz bei dieser Aufgabe! Ich weiß es sehr zu schätzen, dass du so viel Arbeit und Zeit investiert hast, um die Aufgabe abzuschließen. Das zeigt, dass du dranbleibst und dich weiterentwickeln willst – das ist klasse und wirklich wichtig.

Natürlich gibt es immer noch Punkte, an denen man arbeiten kann, aber mach dir keine Sorgen – das ist ganz normal und gehört zum Lernprozess dazu. Bleib dran, und wenn du Fragen hast oder Unterstützung brauchst, sind ich und @FabianSig jederzeit für dich da.

Gute Arbeit, und weiter so! 🚀

2024-11-04 19:36 UTC, merged